version: '3.7'

services:
  web_dev:
    build: ./djtinker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djtinker/:/usr/src/djtinker/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db_dev
  db_dev:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
